#!/usr/bin/env python3

import sys
from pathlib import Path

# Create repo or throw error if already exists
if Path(".mygit").is_dir():
    print("mygit-init: error: .mygit already exists")
else:
    # Initialize top-level
    Path(".mygit").mkdir(exist_ok=True)
    # branches structure
    branches = Path(".mygit/branches")
    branches.mkdir(parents=True, exist_ok=True)
    trunk = branches / "trunk"
    (trunk / "index").mkdir(parents=True, exist_ok=True)
    (trunk / "repository").mkdir(parents=True, exist_ok=True)
    # Set HEAD to default branch
    Path(".mygit/HEAD").write_text("trunk")
    print("Initialized empty mygit repository in .mygit")